server:
  port: 9090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  devtools:
    livereload:
      enabled: true

  datasource:
    hikari:
      pool-name: master-hikari-cp
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/job_manager?allowMultiQueries=true&characterEncoding=utf-8&verifyServerCertificate=true&requireSSL=false&requireSSL=false
      username: jobmanager
      password: manager2023!@
      connection-timeout: 10000
      minimum-idle: 2
      maximum-pool-size: 4
      idle-timeout: 10000
      max-lifetime: 30000
      auto-commit: false
      connection-test-query: SELECT 1
      #driver-class-name: oracle.jdbc.driver.OracleDriver
      #url: jdbc:oracle:thin:@DHDEVDBNEW.corp.doosan.com:1541:DHDEVDB
      #jdbc-url: jdbc:oracle:thin:@DHDEVDBNEW.corp.doosan.com:1541:DHDEVDB
      #username: zshp
      #password: zshp_345#
      #maximum-pool-size: 10
      #minimum-idle: 5
      #connection-timeout: 100000

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.qae.demo

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

# HikariPool에 대한 로깅을 수행함
logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: debug